language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
dist: trusty
env:
  - NODE_ENV=test PORT=3000
cache:
   directories:
     - node_modules
install:
  - npm install
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
